window.esdocSearchIndex = [
  [
    "super-siren/lib/actionfield.js~actionfield",
    "class/lib/ActionField.js~ActionField.html",
    "<span>ActionField</span> <span class=\"search-result-import-path\">super-siren/lib/ActionField.js</span>",
    "class"
  ],
  [
    "super-siren/lib/client.js~client",
    "class/lib/Client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">super-siren/lib/Client.js</span>",
    "class"
  ],
  [
    "super-siren/lib/linkedsubentity.js~linkedsubentity",
    "class/lib/LinkedSubEntity.js~LinkedSubEntity.html",
    "<span>LinkedSubEntity</span> <span class=\"search-result-import-path\">super-siren/lib/LinkedSubEntity.js</span>",
    "class"
  ],
  [
    "super-siren/lib/siren.js~siren",
    "class/lib/Siren.js~Siren.html",
    "<span>Siren</span> <span class=\"search-result-import-path\">super-siren/lib/Siren.js</span>",
    "class"
  ],
  [
    "super-siren/lib/sirenaction.js~sirenaction",
    "class/lib/SirenAction.js~SirenAction.html",
    "<span>SirenAction</span> <span class=\"search-result-import-path\">super-siren/lib/SirenAction.js</span>",
    "class"
  ],
  [
    "super-siren/lib/sirenlink.js~sirenlink",
    "class/lib/SirenLink.js~SirenLink.html",
    "<span>SirenLink</span> <span class=\"search-result-import-path\">super-siren/lib/SirenLink.js</span>",
    "class"
  ],
  [
    "super-siren/lib/actionfield.js~actionfield",
    "variable/index.html#static-variable-actionField",
    "<span>actionField</span> <span class=\"search-result-import-path\">super-siren/lib/ActionField.js</span>",
    "variable"
  ],
  [
    "super-siren/lib/client.js~client",
    "variable/index.html#static-variable-client",
    "<span>client</span> <span class=\"search-result-import-path\">super-siren/lib/Client.js</span>",
    "variable"
  ],
  [
    "super-siren/lib/linkedsubentity.js~linkedsubentity",
    "variable/index.html#static-variable-linkedSubEntity",
    "<span>linkedSubEntity</span> <span class=\"search-result-import-path\">super-siren/lib/LinkedSubEntity.js</span>",
    "variable"
  ],
  [
    "super-siren/lib/siren.js~siren",
    "variable/index.html#static-variable-siren",
    "<span>siren</span> <span class=\"search-result-import-path\">super-siren/lib/Siren.js</span>",
    "variable"
  ],
  [
    "super-siren/lib/sirenaction.js~sirenaction",
    "variable/index.html#static-variable-sirenAction",
    "<span>sirenAction</span> <span class=\"search-result-import-path\">super-siren/lib/SirenAction.js</span>",
    "variable"
  ],
  [
    "super-siren/lib/sirenlink.js~sirenlink",
    "variable/index.html#static-variable-sirenLink",
    "<span>sirenLink</span> <span class=\"search-result-import-path\">super-siren/lib/SirenLink.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/actionfield.js",
    "file/lib/ActionField.js.html",
    "lib/ActionField.js",
    "file"
  ],
  [
    "lib/actionfield.js~actionfield.empty",
    "class/lib/ActionField.js~ActionField.html#static-get-empty",
    "lib/ActionField.js~ActionField.empty",
    "member"
  ],
  [
    "lib/actionfield.js~actionfield.fromjson",
    "class/lib/ActionField.js~ActionField.html#static-method-fromJson",
    "lib/ActionField.js~ActionField.fromJson",
    "method"
  ],
  [
    "lib/client.js",
    "file/lib/Client.js.html",
    "lib/Client.js",
    "file"
  ],
  [
    "lib/client.js~client.action",
    "class/lib/Client.js~Client.html#static-method-action",
    "lib/Client.js~Client.action",
    "method"
  ],
  [
    "lib/client.js~client.addheader",
    "class/lib/Client.js~Client.html#static-method-addHeader",
    "lib/Client.js~Client.addHeader",
    "method"
  ],
  [
    "lib/client.js~client.addparser",
    "class/lib/Client.js~Client.html#static-method-addParser",
    "lib/Client.js~Client.addParser",
    "method"
  ],
  [
    "lib/client.js~client.del",
    "class/lib/Client.js~Client.html#static-method-del",
    "lib/Client.js~Client.del",
    "method"
  ],
  [
    "lib/client.js~client.get",
    "class/lib/Client.js~Client.html#static-method-get",
    "lib/Client.js~Client.get",
    "method"
  ],
  [
    "lib/client.js~client.globalheaders",
    "class/lib/Client.js~Client.html#static-get-globalHeaders",
    "lib/Client.js~Client.globalHeaders",
    "member"
  ],
  [
    "lib/client.js~client.post",
    "class/lib/Client.js~Client.html#static-method-post",
    "lib/Client.js~Client.post",
    "method"
  ],
  [
    "lib/client.js~client.put",
    "class/lib/Client.js~Client.html#static-method-put",
    "lib/Client.js~Client.put",
    "method"
  ],
  [
    "lib/client.js~client.removeheader",
    "class/lib/Client.js~Client.html#static-method-removeHeader",
    "lib/Client.js~Client.removeHeader",
    "method"
  ],
  [
    "lib/linkedsubentity.js",
    "file/lib/LinkedSubEntity.js.html",
    "lib/LinkedSubEntity.js",
    "file"
  ],
  [
    "lib/linkedsubentity.js~linkedsubentity.empty",
    "class/lib/LinkedSubEntity.js~LinkedSubEntity.html#static-get-empty",
    "lib/LinkedSubEntity.js~LinkedSubEntity.empty",
    "member"
  ],
  [
    "lib/linkedsubentity.js~linkedsubentity.fromjson",
    "class/lib/LinkedSubEntity.js~LinkedSubEntity.html#static-method-fromJson",
    "lib/LinkedSubEntity.js~LinkedSubEntity.fromJson",
    "method"
  ],
  [
    "lib/siren.js",
    "file/lib/Siren.js.html",
    "lib/Siren.js",
    "file"
  ],
  [
    "lib/siren.js~siren#constructor",
    "class/lib/Siren.js~Siren.html#instance-constructor-constructor",
    "lib/Siren.js~Siren#constructor",
    "method"
  ],
  [
    "lib/siren.js~siren#embeddedentities",
    "class/lib/Siren.js~Siren.html#instance-get-embeddedEntities",
    "lib/Siren.js~Siren#embeddedEntities",
    "member"
  ],
  [
    "lib/siren.js~siren#embeddedentitiesbyrel",
    "class/lib/Siren.js~Siren.html#instance-method-embeddedEntitiesByRel",
    "lib/Siren.js~Siren#embeddedEntitiesByRel",
    "method"
  ],
  [
    "lib/siren.js~siren#findactionbyname",
    "class/lib/Siren.js~Siren.html#instance-method-findActionByName",
    "lib/Siren.js~Siren#findActionByName",
    "method"
  ],
  [
    "lib/siren.js~siren#findentitiesbyrel",
    "class/lib/Siren.js~Siren.html#instance-method-findEntitiesByRel",
    "lib/Siren.js~Siren#findEntitiesByRel",
    "method"
  ],
  [
    "lib/siren.js~siren#findlinkbyrel",
    "class/lib/Siren.js~Siren.html#instance-method-findLinkByRel",
    "lib/Siren.js~Siren#findLinkByRel",
    "method"
  ],
  [
    "lib/siren.js~siren#linkedentities",
    "class/lib/Siren.js~Siren.html#instance-get-linkedEntities",
    "lib/Siren.js~Siren#linkedEntities",
    "member"
  ],
  [
    "lib/siren.js~siren#linkedentitiesbyrel",
    "class/lib/Siren.js~Siren.html#instance-method-linkedEntitiesByRel",
    "lib/Siren.js~Siren#linkedEntitiesByRel",
    "method"
  ],
  [
    "lib/siren.js~siren#selflink",
    "class/lib/Siren.js~Siren.html#instance-get-selfLink",
    "lib/Siren.js~Siren#selfLink",
    "member"
  ],
  [
    "lib/siren.js~siren.empty",
    "class/lib/Siren.js~Siren.html#static-get-empty",
    "lib/Siren.js~Siren.empty",
    "member"
  ],
  [
    "lib/siren.js~siren.fromjson",
    "class/lib/Siren.js~Siren.html#static-method-fromJson",
    "lib/Siren.js~Siren.fromJson",
    "method"
  ],
  [
    "lib/siren.js~siren.get",
    "class/lib/Siren.js~Siren.html#static-method-get",
    "lib/Siren.js~Siren.get",
    "method"
  ],
  [
    "lib/sirenaction.js",
    "file/lib/SirenAction.js.html",
    "lib/SirenAction.js",
    "file"
  ],
  [
    "lib/sirenaction.js~sirenaction#perform",
    "class/lib/SirenAction.js~SirenAction.html#instance-method-perform",
    "lib/SirenAction.js~SirenAction#perform",
    "method"
  ],
  [
    "lib/sirenaction.js~sirenaction.empty",
    "class/lib/SirenAction.js~SirenAction.html#static-get-empty",
    "lib/SirenAction.js~SirenAction.empty",
    "member"
  ],
  [
    "lib/sirenaction.js~sirenaction.fromjson",
    "class/lib/SirenAction.js~SirenAction.html#static-method-fromJson",
    "lib/SirenAction.js~SirenAction.fromJson",
    "method"
  ],
  [
    "lib/sirenhelpers.js",
    "file/lib/SirenHelpers.js.html",
    "lib/SirenHelpers.js",
    "file"
  ],
  [
    "lib/sirenlink.js",
    "file/lib/SirenLink.js.html",
    "lib/SirenLink.js",
    "file"
  ],
  [
    "lib/sirenlink.js~sirenlink#constructor",
    "class/lib/SirenLink.js~SirenLink.html#instance-constructor-constructor",
    "lib/SirenLink.js~SirenLink#constructor",
    "method"
  ],
  [
    "lib/sirenlink.js~sirenlink#follow",
    "class/lib/SirenLink.js~SirenLink.html#instance-method-follow",
    "lib/SirenLink.js~SirenLink#follow",
    "method"
  ]
]